/**
 * Deterministic restaurant card images (frontend only).
 *
 * Each restaurant_id maps to exactly one cuisine-appropriate photo.
 * The map is generated by scripts/build_restaurant_image_map.py so
 * restaurants of the same cuisine get different images in order.
 */

import restaurantImageMap from "./restaurantImageMap.json";

export const GENERIC_RESTAURANT_IMAGE =
    "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80";

const IMAGE_BY_RESTAURANT_ID = restaurantImageMap;

/**
 * Returns a stable, cuisine-appropriate image URL for this restaurant.
 */
export function getRestaurantImageUrl(restaurant) {
    const restaurantId = restaurant?.restaurant_id;

    if (restaurantId && IMAGE_BY_RESTAURANT_ID[restaurantId]) {
        return IMAGE_BY_RESTAURANT_ID[restaurantId];
    }

    return GENERIC_RESTAURANT_IMAGE;
}
